"""
Views for the canvas_integration app.

This module provides endpoints to:
- start the Canvas OAuth2 flow
- handle the Canvas OAuth2 callback
- trigger asynchronous synchronization of Canvas data
- expose synchronized Canvas resources for the authenticated user
"""

import os
from datetime import timedelta

from django.shortcuts import redirect
from django.utils import timezone
from django.utils.dateparse import parse_datetime
from rest_framework import status, viewsets
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import CanvasAssignment, CanvasCourse, CanvasGrade, CanvasIntegration
from .serializers import (
    CanvasAssignmentSerializer,
    CanvasCourseSerializer,
    CanvasGradeSerializer,
    CanvasIntegrationSerializer,
)
from .services import CanvasService
from .tasks import sync_canvas_data_for_user


class CanvasOAuth2InitiateView(APIView):
    """
    Initiate the Canvas OAuth2 flow for the authenticated user.

    The user is redirected to Canvas using an authorization URL generated by the
    service layer.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        """Redirect the authenticated user to the Canvas authorization page."""
        canvas_base_url = os.environ.get("CANVAS_BASE_URL")
        client_id = os.environ.get("CANVAS_CLIENT_ID")
        redirect_uri = os.environ.get("CANVAS_REDIRECT_URI")

        if not canvas_base_url or not client_id or not redirect_uri:
            return Response(
                {"detail": "Canvas OAuth environment variables are not configured."},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        service = CanvasService(canvas_base_url=canvas_base_url)
        authorization_url = service.get_authorization_url(
            redirect_uri=redirect_uri,
            client_id=client_id,
        )

        # Keep a simple state parameter so the callback can identify the user.
        separator = "&" if "?" in authorization_url else "?"
        authorization_url = f"{authorization_url}{separator}state={request.user.id}"
        return redirect(authorization_url)


class CanvasOAuth2CallbackView(APIView):
    """
    Handle the OAuth2 callback from Canvas.

    This view exchanges the received authorization code for tokens and stores
    the integration for the user identified by the `state` parameter.
    """

    permission_classes = [AllowAny]

    def get(self, request, *args, **kwargs):
        """Exchange the authorization code for tokens and persist them locally."""
        code = request.query_params.get("code")
        user_id = request.query_params.get("state") or request.query_params.get("user_id")

        if not code:
            return Response(
                {"detail": "The 'code' query parameter is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        if not user_id:
            return Response(
                {
                    "detail": (
                        "The callback requires a user identifier in 'state' or 'user_id'."
                    )
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        canvas_base_url = os.environ.get("CANVAS_BASE_URL")
        client_id = os.environ.get("CANVAS_CLIENT_ID")
        client_secret = os.environ.get("CANVAS_CLIENT_SECRET")
        redirect_uri = os.environ.get("CANVAS_REDIRECT_URI")

        if not canvas_base_url or not client_id or not client_secret or not redirect_uri:
            return Response(
                {"detail": "Canvas OAuth environment variables are not configured."},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        service = CanvasService(canvas_base_url=canvas_base_url)

        try:
            token_data = service.exchange_code_for_tokens(
                code=code,
                redirect_uri=redirect_uri,
                client_id=client_id,
                client_secret=client_secret,
            )
        except Exception as exc:
            return Response(
                {"detail": f"Canvas token exchange failed: {str(exc)}"},
                status=status.HTTP_502_BAD_GATEWAY,
            )

        access_token = token_data.get("access_token")
        refresh_token = token_data.get("refresh_token")
        expires_at = token_data.get("expires_at")
        expires_in = token_data.get("expires_in")

        if not access_token:
            return Response(
                {"detail": "Canvas did not return an access token."},
                status=status.HTTP_502_BAD_GATEWAY,
            )

        service.access_token = access_token
        canvas_user_id = None
        try:
            profile_data = service.get_user_profile()
            if profile_data.get("id") is not None:
                canvas_user_id = str(profile_data["id"])
        except Exception:
            # Persist the integration even if the profile fetch fails.
            canvas_user_id = None

        token_expires_at = None
        if isinstance(expires_at, str):
            token_expires_at = parse_datetime(expires_at)
        elif expires_in:
            token_expires_at = timezone.now() + timedelta(seconds=int(expires_in))

        try:
            integration, _ = CanvasIntegration.objects.update_or_create(
                user_id=user_id,
                defaults={
                    "access_token": access_token,
                    "refresh_token": refresh_token,
                    "canvas_user_id": canvas_user_id,
                    "token_expires_at": token_expires_at,
                },
            )
        except Exception as exc:
            return Response(
                {"detail": f"Failed to persist Canvas integration: {str(exc)}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        return Response(
            CanvasIntegrationSerializer(integration).data,
            status=status.HTTP_200_OK,
        )


class CanvasSyncDataView(APIView):
    """
    Trigger asynchronous synchronization of Canvas data for the authenticated user.
    """

    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        """Queue the Canvas sync task for the current user."""
        if not CanvasIntegration.objects.filter(user=request.user).exists():
            return Response(
                {"detail": "Canvas integration not found for the authenticated user."},
                status=status.HTTP_404_NOT_FOUND,
            )

        task = sync_canvas_data_for_user.delay(request.user.id)
        return Response(
            {
                "message": "Canvas data synchronization started.",
                "task_id": task.id,
            },
            status=status.HTTP_202_ACCEPTED,
        )


class CanvasCourseViewSet(viewsets.ReadOnlyModelViewSet):
    """Read-only access to synchronized Canvas courses for the current user."""

    serializer_class = CanvasCourseSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Return only courses belonging to the authenticated user."""
        return CanvasCourse.objects.filter(user=self.request.user).order_by("name")


class CanvasAssignmentViewSet(viewsets.ReadOnlyModelViewSet):
    """Read-only access to synchronized Canvas assignments for the current user."""

    serializer_class = CanvasAssignmentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Return only assignments from courses owned by the authenticated user."""
        return CanvasAssignment.objects.filter(
            course__user=self.request.user
        ).select_related("course").order_by("due_date", "name")


class CanvasGradeViewSet(viewsets.ReadOnlyModelViewSet):
    """Read-only access to synchronized Canvas grades for the current user."""

    serializer_class = CanvasGradeSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        """Return only grades belonging to the authenticated user."""
        return CanvasGrade.objects.filter(user=self.request.user).select_related(
            "assignment",
            "assignment__course",
        ).order_by("-graded_at", "-updated_at")
