# Generated by Django 5.2.12 on 2026-04-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the diagnostic test.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Short description explaining the purpose of the test.')),
                ('related_skill', models.ForeignKey(help_text='Skill evaluated by this diagnostic test.', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='study_content.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Statement or prompt shown to the student.')),
                ('question_type', models.CharField(default='multiple_choice', help_text='Type of question, for example multiple_choice or open_text.', max_length=30)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of the question inside the test.')),
                ('test', models.ForeignKey(help_text='Diagnostic test to which this question belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.diagnostictest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text displayed for this answer choice.', max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Indicates whether this is the correct answer.')),
                ('question', models.ForeignKey(help_text='Question to which this choice belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='diagnostics.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Free-text answer submitted by the student when applicable.', null=True)),
                ('is_correct', models.BooleanField(default=False, help_text="Stores whether the student's answer was correct.")),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the answer was submitted.')),
                ('chosen_choice', models.ForeignKey(blank=True, help_text='Choice selected by the student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='diagnostics.choice')),
                ('question', models.ForeignKey(help_text='Question answered by the student.', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='diagnostics.question')),
                ('student', models.ForeignKey(help_text='Student who answered the question.', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.DecimalField(decimal_places=2, default=0.0, help_text='Current score or mastery value for the student in this skill.', max_digits=5)),
                ('completed', models.BooleanField(default=False, help_text='Indicates whether the student completed the diagnostic flow.')),
                ('last_evaluated', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest progress evaluation.')),
                ('skill', models.ForeignKey(help_text='Skill for which progress is being recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='study_content.skill')),
                ('student', models.ForeignKey(help_text='Student whose progress is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
