# Generated by Django 5.2.12 on 2026-04-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the school year, for example '9o Ano' or '1a Serie EM'.", max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill developed in this topic.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the content item.', max_length=200)),
                ('description', models.TextField(help_text='Short description or summary of the content.')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('pdf', 'PDF'), ('exercise', 'Exercise')], help_text='Type of educational content.', max_length=20)),
                ('skill', models.ForeignKey(help_text='Skill to which this content item is related.', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='study_content.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject, for example Mathematics or History.', max_length=100)),
                ('school_year', models.ForeignKey(help_text='School year to which this subject belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='study_content.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the topic covered within the subject.', max_length=150)),
                ('subject', models.ForeignKey(help_text='Subject to which this topic belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='study_content.subject')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(help_text='Topic to which this skill belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='study_content.topic'),
        ),
    ]
