# Generated by Django 5.2.12 on 2026-04-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_score', models.DecimalField(decimal_places=2, default=0.0, help_text="Weekly score representing the student's effort.", max_digits=8)),
                ('ranking_position', models.PositiveIntegerField(default=0, help_text='Position of the student in the weekly ranking.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest ranking update.')),
                ('student', models.OneToOneField(help_text='Student whose effort ranking is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='effort_ranking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort_score', models.DecimalField(decimal_places=2, default=0.0, help_text="Effort score associated with the student's work.", max_digits=8)),
                ('grade_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Grade score obtained for the assignment.', max_digits=8)),
                ('correlation_note', models.TextField(blank=True, help_text='Optional note about the observed effort/grade relationship.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas_assignment', models.ForeignKey(help_text='Canvas assignment used for the grade correlation analysis.', on_delete=django.db.models.deletion.CASCADE, related_name='grade_correlations', to='canvas_integration.canvasassignment')),
                ('student', models.ForeignKey(help_text='Student linked to this grade correlation record.', on_delete=django.db.models.deletion.CASCADE, related_name='grade_correlations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the mission.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of what the student should do.')),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for completing the mission.', null=True)),
                ('status', models.CharField(default='pending', help_text='Current mission status, for example pending or completed.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas_assignment', models.ForeignKey(blank=True, help_text='Related Canvas assignment, when the mission came from Canvas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='canvas_integration.canvasassignment')),
                ('student', models.ForeignKey(help_text='Student responsible for this mission.', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the mission was completed.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the mission completion.')),
                ('mission', models.ForeignKey(help_text='Mission that was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='pulse_missions.mission')),
            ],
        ),
    ]
