# Generated by Django 5.2.12 on 2026-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_assignment_id', models.CharField(help_text='Assignment identifier from Canvas.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name of the assignment.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Assignment description as provided by Canvas.')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date of the assignment in Canvas.', null=True)),
                ('points_possible', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum score possible for the assignment.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_course_id', models.CharField(help_text='Course identifier from Canvas.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name of the Canvas course.', max_length=255)),
                ('course_code', models.CharField(blank=True, help_text='Short code for the Canvas course.', max_length=100, null=True)),
                ('enrollment_state', models.CharField(blank=True, help_text='Enrollment state of the user in this course.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric score received for the assignment.', max_digits=8, null=True)),
                ('grade', models.CharField(blank=True, help_text='Letter or textual grade returned by Canvas.', max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submission timestamp recorded by Canvas.', null=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='Timestamp when the assignment was graded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanvasIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='OAuth access token used to call the Canvas API.')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token used to renew access when available.', null=True)),
                ('canvas_user_id', models.CharField(blank=True, help_text='Identifier of the user in Canvas.', max_length=100, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp for the current access token.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
