# Generated by Django 5.2.12 on 2026-04-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canvascourse',
            name='user',
            field=models.ForeignKey(help_text='User to whom this Canvas course is linked.', on_delete=django.db.models.deletion.CASCADE, related_name='canvas_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvasassignment',
            name='course',
            field=models.ForeignKey(help_text='Canvas course to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='canvas_integration.canvascourse'),
        ),
        migrations.AddField(
            model_name='canvasgrade',
            name='assignment',
            field=models.ForeignKey(help_text='Assignment to which this grade belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='canvas_integration.canvasassignment'),
        ),
        migrations.AddField(
            model_name='canvasgrade',
            name='user',
            field=models.ForeignKey(help_text='User who received this grade.', on_delete=django.db.models.deletion.CASCADE, related_name='canvas_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvasintegration',
            name='user',
            field=models.OneToOneField(help_text='User who owns this Canvas integration.', on_delete=django.db.models.deletion.CASCADE, related_name='canvas_integration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='canvasgrade',
            unique_together={('assignment', 'user')},
        ),
    ]
